'use strict';

const POLICIES = {
  none: {},
  winner_focus: {
    AUDUSD: { sessions: ['OVERLAP'], minTier: 'DIAMOND' },
    EURJPY: { sessions: ['OVERLAP'], minTier: 'DIAMOND' },
    GBPUSD: { sessions: ['LONDON', 'NEW_YORK', 'OVERLAP'], minTier: 'DIAMOND' },
    USDCAD: { sessions: ['NEW_YORK', 'OVERLAP'], minTier: 'DIAMOND' },
    GBPJPY: { sessions: ['NEW_YORK', 'OVERLAP'], minTier: 'GOLD' },
  },
  selective_pairs: {
    AUDUSD: { sessions: ['OVERLAP'], minTier: 'DIAMOND' },
    EURJPY: { sessions: ['OVERLAP'], minTier: 'DIAMOND' },
    GBPUSD: { sessions: ['LONDON', 'NEW_YORK', 'OVERLAP'], minTier: 'DIAMOND' },
    USDCAD: { sessions: ['NEW_YORK', 'OVERLAP'], minTier: 'DIAMOND' },
  },
  prune_losers: {
    EURJPY: { sessions: ['OVERLAP'], minTier: 'DIAMOND' },
    USDCAD: { sessions: ['NEW_YORK', 'OVERLAP'], minTier: 'DIAMOND' },
  },
  quality_prune: {
    EURJPY: { sessions: ['OVERLAP'], minTier: 'DIAMOND' },
    USDCAD: { sessions: ['NEW_YORK', 'OVERLAP'], minTier: 'DIAMOND' },
    AUDUSD: { sessions: ['ASIAN', 'OVERLAP'], minTier: 'GOLD' },
    USDCHF: { sessions: ['LONDON', 'OVERLAP'], minTier: 'GOLD' },
  },
  real15m_focus: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: { sessions: ['LONDON', 'NEW_YORK', 'OVERLAP'], minTier: 'GOLD' },
    USDCHF: { sessions: ['LONDON', 'OVERLAP'], minTier: 'GOLD' },
    GBPJPY: { sessions: ['NEW_YORK', 'OVERLAP'], minTier: 'GOLD' },
    EURJPY: { sessions: ['OVERLAP'], minTier: 'GOLD' },
  },
  real15m_growth: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURJPY: { sessions: ['OVERLAP'] },
  },
  mixed_growth_v1: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURJPY: { disabled: true },
    EURUSD: { sessions: ['NEW_YORK', 'OVERLAP'] },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'] },
  },
  mixed_growth_v2: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURJPY: { disabled: true },
    EURUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_B'] },
    USDCHF: { allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
    GBPJPY: { allowedEntryTypes: ['TYPE_A', 'TYPE_B', 'TYPE_D'] },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  mixed_growth_v3: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_B'] },
    USDCHF: { allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
    GBPJPY: { allowedEntryTypes: ['TYPE_A', 'TYPE_B', 'TYPE_D'] },
    EURJPY: { allowedEntryTypes: ['TYPE_A', 'TYPE_B'], minTier: 'GOLD' },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  mixed_growth_v4: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_B'] },
    USDCHF: { allowedEntryTypes: ['TYPE_A', 'TYPE_B'], minTier: 'GOLD' },
    GBPJPY: { allowedEntryTypes: ['TYPE_B'] },
    EURJPY: { allowedEntryTypes: ['TYPE_B'], minTier: 'GOLD' },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  target_growth_v1: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_B'], h4ScanWindowMinutes: 60, maxMonthlyLossR: 4 },
    USDCHF: { allowedEntryTypes: ['TYPE_A', 'TYPE_B'], minTier: 'GOLD', h4ScanWindowMinutes: 60 },
    GBPJPY: { allowedEntryTypes: ['TYPE_B'], h4ScanWindowMinutes: 60, maxMonthlyLossR: 8 },
    EURJPY: { allowedEntryTypes: ['TYPE_A'], minTier: 'GOLD', h4ScanWindowMinutes: 120, maxMonthlyLossR: 6 },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  target_growth_v2: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_B'], h4ScanWindowMinutes: 60, maxMonthlyLossR: 4 },
    USDCHF: { allowedEntryTypes: ['TYPE_A', 'TYPE_B'], minTier: 'GOLD', h4ScanWindowMinutes: 60 },
    GBPJPY: { allowedEntryTypes: ['TYPE_B'], h4ScanWindowMinutes: 90, maxMonthlyLossR: 8 },
    EURJPY: { allowedEntryTypes: ['TYPE_A'], minTier: 'GOLD', h4ScanWindowMinutes: 120, maxMonthlyLossR: 6 },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  target_growth_v3: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      h4ScanWindowMinutes: 60,
      maxMonthlyLossR: 4,
      blockedHoursUTC: [16],
    },
    USDCHF: { allowedEntryTypes: ['TYPE_A', 'TYPE_B'], minTier: 'GOLD', h4ScanWindowMinutes: 60 },
    GBPJPY: { allowedEntryTypes: ['TYPE_B'], h4ScanWindowMinutes: 90, maxMonthlyLossR: 8 },
    EURJPY: {
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 120,
      maxMonthlyLossR: 6,
      blockedHoursUTC: [4],
    },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  target_growth_v4: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      h4ScanWindowMinutes: 60,
      maxMonthlyLossR: 4,
      blockedHoursUTC: [16],
    },
    USDCHF: {
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 60,
      blockedRegimes: ['RANGING'],
    },
    GBPJPY: { allowedEntryTypes: ['TYPE_B'], h4ScanWindowMinutes: 90, maxMonthlyLossR: 8 },
    EURJPY: {
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 120,
      maxMonthlyLossR: 6,
      blockedHoursUTC: [4],
    },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  target_growth_v5: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      h4ScanWindowMinutes: 60,
      maxMonthlyLossR: 4,
      blockedHoursUTC: [16],
    },
    USDCHF: {
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 60,
      blockedRegimes: ['RANGING'],
    },
    GBPJPY: { allowedEntryTypes: ['TYPE_B'], h4ScanWindowMinutes: 120, maxMonthlyLossR: 8 },
    EURJPY: {
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 120,
      maxMonthlyLossR: 6,
      blockedHoursUTC: [4],
    },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  target_growth_v6: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      h4ScanWindowMinutes: 60,
      maxMonthlyLossR: 4,
      blockedHoursUTC: [16],
    },
    USDCHF: {
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 60,
      blockedRegimes: ['RANGING'],
    },
    GBPJPY: {
      allowedEntryTypes: ['TYPE_B'],
      h4ScanWindowMinutes: 120,
      maxMonthlyLossR: 8,
      blockedDirections: ['SELL'],
    },
    EURJPY: {
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 120,
      maxMonthlyLossR: 6,
      blockedHoursUTC: [4],
      blockedLevelRegimes: { ORDER_BLOCK: ['RANGING', 'TRENDING'] },
    },
    XAUUSD: { sessions: ['NEW_YORK', 'OVERLAP'], allowedEntryTypes: ['TYPE_A', 'TYPE_B'] },
  },
  audit_focus_v1: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    GBPJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      minTier: 'GOLD',
      blockedHoursUTC: [16],
      h4ScanWindowMinutes: 60,
    },
    USDCHF: {
      sessions: ['LONDON'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 60,
      blockedRegimes: ['RANGING'],
    },
    EURJPY: {
      sessions: ['ASIAN'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 120,
    },
    XAUUSD: {
      sessions: ['NEW_YORK'],
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['WEAK_TREND'],
    },
  },
  audit_focus_v2: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      minTier: 'GOLD',
      blockedHoursUTC: [16],
      h4ScanWindowMinutes: 60,
    },
    USDCHF: {
      sessions: ['LONDON'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 60,
      blockedRegimes: ['RANGING'],
    },
    GBPJPY: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      minTier: 'GOLD',
      blockedDirections: ['SELL'],
      h4ScanWindowMinutes: 120,
    },
    EURJPY: {
      sessions: ['ASIAN'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 120,
    },
    XAUUSD: {
      sessions: ['NEW_YORK'],
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['WEAK_TREND'],
    },
  },
  audit_focus_v3: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['RANGING'],
      blockedHoursUTC: [16],
      h4ScanWindowMinutes: 60,
    },
    USDCHF: {
      sessions: ['LONDON'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      blockedRegimes: ['TRENDING', 'RANGING'],
      h4ScanWindowMinutes: 60,
    },
    GBPJPY: {
      allowedEntryTypes: ['TYPE_B'],
      blockedRegimes: ['TRENDING', 'WEAK_TREND'],
      blockedDirections: ['SELL'],
      h4ScanWindowMinutes: 120,
    },
    EURJPY: {
      sessions: ['ASIAN'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      blockedRegimes: ['TRENDING'],
      h4ScanWindowMinutes: 120,
    },
    XAUUSD: {
      sessions: ['NEW_YORK'],
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['WEAK_TREND'],
    },
  },
  audit_focus_v4: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['RANGING'],
      blockedHoursUTC: [16],
      h4ScanWindowMinutes: 60,
    },
    USDCHF: {
      sessions: ['LONDON'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      blockedRegimes: ['TRENDING', 'RANGING'],
      h4ScanWindowMinutes: 60,
    },
    GBPJPY: {
      allowedEntryTypes: ['TYPE_B'],
      blockedRegimes: ['TRENDING', 'WEAK_TREND'],
      blockedDirections: ['SELL'],
      h4ScanWindowMinutes: 120,
    },
    EURJPY: {
      sessions: ['ASIAN'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      h4ScanWindowMinutes: 120,
    },
    XAUUSD: {
      sessions: ['NEW_YORK'],
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['WEAK_TREND'],
    },
  },
  audit_focus_v5: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['RANGING'],
      blockedHoursUTC: [16],
      h4ScanWindowMinutes: 60,
    },
    USDCHF: {
      sessions: ['LONDON'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      blockedRegimes: ['TRENDING', 'RANGING'],
      h4ScanWindowMinutes: 60,
    },
    GBPJPY: {
      allowedEntryTypes: ['TYPE_B'],
      blockedRegimes: ['TRENDING', 'WEAK_TREND'],
      blockedDirections: ['SELL'],
      h4ScanWindowMinutes: 120,
    },
    EURJPY: {
      sessions: ['ASIAN'],
      allowedEntryTypes: ['TYPE_A'],
      minTier: 'GOLD',
      maxAdx: 45,
      blockedHoursUTC: [4],
      h4ScanWindowMinutes: 120,
    },
    XAUUSD: {
      sessions: ['NEW_YORK'],
      allowedEntryTypes: ['TYPE_A', 'TYPE_B'],
      minTier: 'GOLD',
      blockedRegimes: ['WEAK_TREND'],
    },
  },
  scalp_v1: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    XAUUSD: { disabled: true },
    EURUSD: {
      sessions: ['NEW_YORK', 'OVERLAP'],
      allowedEntryTypes: ['SCALP_CONTINUATION'],
      minTier: 'SILVER',
      blockedRegimes: ['RANGING'],
      maxAdx: 45,
    },
    USDCHF: {
      sessions: ['LONDON'],
      allowedEntryTypes: ['SCALP_CONTINUATION'],
      minTier: 'SILVER',
      blockedRegimes: ['RANGING'],
      maxAdx: 45,
    },
    GBPJPY: {
      sessions: ['ASIAN', 'NEW_YORK'],
      allowedEntryTypes: ['SCALP_CONTINUATION'],
      minTier: 'SILVER',
      allowedRegimes: ['RANGING', 'WEAK_TREND'],
      blockedDirections: ['SELL'],
      maxAdx: 30,
    },
    EURJPY: {
      sessions: ['ASIAN'],
      allowedEntryTypes: ['SCALP_CONTINUATION'],
      minTier: 'SILVER',
      maxAdx: 45,
      blockedHoursUTC: [4],
    },
  },
  scalp_v2: {
    GBPUSD: { disabled: true },
    USDCAD: { disabled: true },
    AUDUSD: { disabled: true },
    USDJPY: { disabled: true },
    USDCHF: { disabled: true },
    XAUUSD: { disabled: true },
    EURUSD: {
      sessions: ['OVERLAP'],
      allowedEntryTypes: ['SCALP_CONTINUATION'],
      minTier: 'SILVER',
      allowedRegimes: ['TRENDING', 'WEAK_TREND'],
      allowedHoursUTC: [13, 14],
      maxAdx: 45,
    },
    GBPJPY: {
      sessions: ['NEW_YORK'],
      allowedEntryTypes: ['SCALP_CONTINUATION'],
      minTier: 'SILVER',
      allowedRegimes: ['RANGING'],
      allowedHoursUTC: [16, 17, 19, 20],
      blockedDirections: ['SELL'],
      maxAdx: 15,
    },
    EURJPY: {
      sessions: ['ASIAN'],
      allowedEntryTypes: ['SCALP_CONTINUATION'],
      minTier: 'SILVER',
      allowedRegimes: ['RANGING', 'TRENDING'],
      allowedHoursUTC: [0, 1, 3, 5, 6],
      maxAdx: 45,
    },
  },
};

function getPairPolicy(name = 'none') {
  return POLICIES[name] || POLICIES.none;
}

module.exports = {
  POLICIES,
  getPairPolicy,
};
